apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: homepage
  wait: true